---
version: '3'
services:
  identidock:
    build: .     
    expose:
      - "9090"
    environment:
      ENV: PROD
    volumes:
      - ./app:/app 
    depends_on:
      - dnmonster
      - redis
    links:
      - dnmonster 
      - redis
  dnmonster:
    image: amouat/dnmonster:1.0
  redis:
    image: redis:3.0
